vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
       food_images:
           uri_prefix: /images/foods
           upload_destination: '%kernel.project_dir%/public/images/foods'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
